#
# Storage configuration file.
#
# @author Matthew Casey
#
# (c) University of Surrey 2019
#

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

aws:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :s3, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :s3, :secret_access_key) %>
  region: <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :region) %>
  bucket: <%= Rails.application.credentials.dig(Rails.env.to_sym, :aws, :bucket) %>
